magnet:
  material: player_head
  head_value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJhOGViYzRjNmE4MTczMDk0NzQ5OWJmN2UxZDVlNzNmZWQ2YzFiYjJjMDUxZTk2ZDM1ZWIxNmQyNDYxMGU3In19fQ=="
  lore:
    - "<yellow>Притягивает предметы лежащие предметы"
    - "<yellow>Радиус: <radius> блоков"
  name: "<blue>Маг<red>нит"

radius: 3
speed: 0.3