permission-required: false # Разрешение magnet.use

particles:
  enabled: true
  #Список партиклов
  #https://minecraft.wiki/w/Particles_(Java_Edition)
  type: END_ROD

tasks:
  # Время между притягиванием предметов (ТИКИ)
  # 20 тиков в 1 секунде
  magnet-period: 10


  # Время между проверкой нагрузки
  performance-period: 1200
  cpu-limit: 90
  ram-limit: 90

default-item:
  name: "<red>Маг<blue>нит"
  type: PLAYER_HEAD
  head-value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJhOGViYzRjNmE4MTczMDk0NzQ5OWJmN2UxZDVlNzNmZWQ2YzFiYjJjMDUxZTk2ZDM1ZWIxNmQyNDYxMGU3In19fQ=="
  lore:
    - "<light_purple>Обладает возможностью притягивать предметы"
    - "<light_purple>Радиус: <white><radius> бл."
    - "<light_purple>Сила: <white><strength>"
    - "<light_purple>Лимит: <white><limit>"
    - "<white>"
    - "<gray>©PPFSS"